### PR TITLE
Correct a typo on the home page.

### PR DESCRIPTION
**Pull request by onlywade**

### CODE REVIEW

**Comment by kvz** [comment]
Yes indeed :) would one-week be the correct spelling for that? @ajvanloon?

**Comment by AJvanLoon** [comment]
Yeah indeed. It should be hyphenated. one-week is correct. Thanks for correcting it!

**Comment by kvz** [comment]
@onlywade Would you want to update it? Then we can merge this PR and get your contribution cemented in tus.io history :)

**Comment by Acconut** [comment]
Took care of this by myself. I still want to thank you, @onlywade, for finding this mistake :)

**Pull request closed without merging**
