### PR TITLE
Demo: animated reset for progress bar upon finishing upload

### PR DESCRIPTION
**Pull request by fahad19**
Refs #25 

## Preview

(much smoother in real life than captured GIF)

tl_progress_bar

Will think about how to highlight the generated link/button for the newly uploaded file in next PR.

### CODE REVIEW

**Comment by kvz** [comment]
Very nice Fahad! <3

**Comment by Acconut** [comment]
Looks awesome :heart:
@kvz: Has this already been deployed? It does not appear for me in Firefox.

**Comment by kvz** [comment]
I did, yes..

**Comment by Acconut** [comment]
After redeploying it works now for me :)

**Comment by kvz** [comment]
Hm. Must have been cause my assetbuilding is still failing in a non-fatal way https://github.com/tus/tus.io/issues/26

**Pull request merged**
