### PR TITLE
Transloadit bar + GitHub ribbon replacement

### PR DESCRIPTION
**Pull request by nqst**
## Changes

1. Added the Transloadit bar
2. Replaced the oldie, non-hiDPI friendly Github ribbon with a more modern one, similar to what we use on [uppy.io](url).

**Note:** Not sure if `tus is a product made by Transloadit` is the best possible copy. Feel free to modify!

## Preview

image

### CODE REVIEW

**Comment by Acconut** [comment]
Thanks for the changes, Alex! The new GitHub ribbon looks very nice but I have two concerns about the "Transloadit bar":

1. As you also mentioned calling tus a product is not really correct. tus is rather more a project consisting of the actual software implementations (the official ones and from other people), the specification and the community.
2. I would also be cautious about the phrase "made by Transloadit". While undoubtedly Transloadit has spent a lot of money on tus, large parts of tus-js-client and tusd were also provided by external contributors. And tus-node-server was entirely developed by a non-Transloadian. I am not against Transloadit showing how much resources have been spent on a free and open-source project like tus but I think we should discuss whether we want to continue the "tus is owned by the community"-branding or if we want to start calling "tus is made by Transloadit".

**Comment by Acconut** [comment]
Just to clarify, I am always open to discuss about how we should continue with tus :)

**Comment by kvz** [comment]
> tus is an open source project started by Transloadit

?

**Comment by Acconut** [comment]
Would be fine for me, yes

**Comment by kvz** [comment]
I wonder if it isn't correct to say 

> tus is an open source project by Transloadit

tho. i do think we offered this project to the community. So it's like, it's `of ` the community but `by` TL?

Or how about 

>tus is an open source project from Transloadit

**Comment by Acconut** [comment]
I would also be fine with those options :+1:

**Comment by nqst** [comment]
Done!

I used this: `tus is an open-source project by Transloadit`

Guess it's ready to merge.

**Comment by kvz** [comment]
:ship: thanks Alex!

**Pull request merged**
