### PR TITLE
blog: Add post about IETF update

### PR DESCRIPTION
**Pull request by Acconut**
This is a brief blog post describing the latest development on working with the IETF on the resumable uploads standard.

### CODE REVIEW

**Comment by Acconut** [comment]
This blog post is the first one that uses tables apparently:

image

@nickrttn @nqst Could you recommend an easy way to style them?

**Comment by nqst** [comment]
Added some styles:

Screenshot 2023-08-10 at 12 27 17@2x

**Comment by Acconut** [comment]
Thank you very much! That looks great!

**Comment by AJvanLoon** [comment]
Fixed a few small errors and slightly reworded certain bits to my liking. Let me know if I interpreted/phrased anything in the wrong way!

**Comment by Acconut** [comment]
Thank you very much for the feedback, @AJvanLoon!

**Pull request merged**
