### PR TITLE
Design improvements - round one

### PR DESCRIPTION
**Pull request by nqst**
Polished typography, slightly improved layout, added custom font and fixed some minor issues.

Screenshot 2020-06-05 at 11 04 25
Screenshot 2020-06-05 at 11 04 32
Screenshot 2020-06-05 at 11 04 35
Screenshot 2020-06-05 at 11 04 37
Screenshot 2020-06-05 at 11 04 39

### CODE REVIEW

**Comment by kvz** [comment]
This is very wholesome :heart_eyes_cat:

**Comment by Acconut** [comment]
amazing, thank you, Alex!

Is it intended that on the demo page the paragraphs don't have full width (compared to the header or the horizontal lines) but are also not centered?

image

**Comment by nqst** [comment]
It was intended, yeah: I wanted to keep the layout width (so that some sections are not that narrow), but shorten the paragraphs and list items width — so they're easier to read.

Does it look fine for you, or you'd rather prefer more classic / centered layout?

**Comment by Acconut** [comment]
I didn't notice it in the beginning but after spotting it, I found it a bit odd. I am no opposing it, though, and we can keep it :)

**Pull request merged**
