### PR TITLE
Update logos.yml

### PR DESCRIPTION
**Pull request by deebash**
Please review and add our app logo. Without Tus, it'll be a headache for us. Thanks for saving our time

### CODE REVIEW

**Comment by kvz** [comment]
Happy to merge this, please first make the YAML valid though :ok_hand:

**Comment by kvz** [comment]
Oh and it seems your logo isn't included, either

**Comment by deebash** [comment]
> Oh and it seems your logo isn't included, either

When I click Upload Files button, "Uploads are disabled. You need push access....." message is shown.

**Comment by kvz** [comment]
You can also add a full URL, then we'll inline later on

**Comment by deebash** [comment]
> You can also add a full URL, then we'll inline later on
Full URL is now added. Thank you

**Comment by kvz** [comment]
Merged! :pray:

**Pull request merged**
